DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE PRODUCT (
    PRO_ID INT PRIMARY KEY,
    PRO_NAME VARCHAR(50),
    PRO_PRICE INT,
    PRO_COM VARCHAR(50)
);

INSERT INTO PRODUCT VALUES
(101, 'Keyboard', 350, 'Logitech'),
(102, 'Mouse', 250, 'HP'),
(103, 'ZIP DRIVE', 500, 'SanDisk'),
(104, 'Speaker', 450, 'JBL'),
(105, 'Monitor', 1500, 'Samsung'),
(106, 'Printer', 1200, 'Canon'),
(107, 'Laptop', 5000, 'Dell'),
(108, 'Microphone', 800, 'Sony'),
(109, 'Mouse Pad', 150, 'Logitech'),
(110, 'Printer Cable', 200, 'HP');

SELECT * FROM PRODUCT;

SELECT * FROM PRODUCT
WHERE PRO_PRICE < 1000 AND PRO_COM = 'DATAFIX';

SELECT * FROM PRODUCT
WHERE PRO_PRICE < 1000 OR PRO_COM = 'DATAFIX';

SELECT * FROM PRODUCT
WHERE PRO_NAME LIKE 'M%';

SELECT * FROM PRODUCT
WHERE PRO_NAME LIKE '%DRIVE';

SELECT * FROM PRODUCT
WHERE PRO_NAME LIKE '%PRINT%';

SELECT * FROM PRODUCT
WHERE PRO_PRICE = (SELECT MIN(PRO_PRICE) FROM PRODUCT);

SELECT * FROM PRODUCT
WHERE PRO_PRICE = (SELECT MAX(PRO_PRICE) FROM PRODUCT);

UPDATE PRODUCT
SET PRO_PRICE = 600
WHERE PRO_ID = 104;

SELECT * FROM PRODUCT
WHERE PRO_ID = 104;

DELETE FROM PRODUCT
WHERE PRO_ID = 103;

SELECT * FROM PRODUCT;